networks:
  app-network:
    driver: bridge

services:
  react-app:
    build:
      context: /home/devops/frontend
      dockerfile: Dockerfile
    ports:
      - "8091:80"
    networks:
      - app-network